---
# Config file for OCP GA 4.4 stable channel

RUN:
  client_version: '4.4-ga'

DEPLOYMENT:
  ocp_url_template: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{version}/{file_name}-{os_type}-{version}.tar.gz"
  installer_version: "4.4-ga"
  ocp_channel: "fast"
ENV_DATA:
  vm_template: 'rhcos-4.4.0-rc.1-x86_64-vmware.x86_64'
  # Once 4.4 GA we should move to new template without -rc suffix (see below)
  # vm_template: 'rhcos-4.4.0-x86_64-vmware'
  # rhcos_ami: 'ami-06c85f9d106577272'
  # If rhcos_ami is not specified the ID for aws upi deployments will be fetched from
  # https://raw.githubusercontent.com/openshift/installer/release-4.4/data/data/rhcos.json
