---
# Config file for nightly OCP 4.6
RUN:
  client_version: '4.6.0-0.nightly'
DEPLOYMENT:
  installer_version: "4.6.0-0.nightly"
  terraform_version: "0.12.26"
ENV_DATA:
  vm_template: 'rhcos-46.82.202008260918-0-vmware.x86_64'
  # rhcos_ami: 'ami-06c85f9d106577272'
  # If rhcos_ami is not specified the ID for aws upi deployments will be fetched from
  # https://raw.githubusercontent.com/openshift/installer/release-4.6/data/data/rhcos.json
