---
# Config file for OCP GA 4.6 stable channel minus 1 version

RUN:
  client_version: '4.6-ga'

DEPLOYMENT:
  ocp_url_template: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{version}/{file_name}-{os_type}-{version}.tar.gz"
  installer_version: "4.6-ga"
  terraform_version: "0.12.31"
  ignition_version: "3.1.0"
  ocp_channel: "stable"
  ocp_version_index: -2
ENV_DATA:
  vm_template: 'rhcos-46.82.202010011740-0-vmware.x86_64'
