---
# Config file for nightly OCP 4.10
RUN:
  client_version: "4.10.0-0.nightly-2021-12-18-034942"
DEPLOYMENT:
  installer_version: "4.10.0-0.nightly-2021-12-18-034942"
  terraform_version: "0.12.26"
  # ignition_version can be found here
  # https://docs.openshift.com/container-platform/4.7/post_installation_configuration/machine-configuration-tasks.html#machine-config-overview-post-install-machine-configuration-tasks
  ignition_version: "3.2.0"
ENV_DATA:
  vm_template: "rhcos-410.84.202112040202-0-vmware.x86_64"
