---
# Config file for nightly OCP 4.16
RUN:
  client_version: "4.16.0-0.nightly"
DEPLOYMENT:
  installer_version: "4.16.0-0.nightly"
  terraform_version: "1.0.11"
  # ignition_version can be found here
  # https://docs.openshift.com/container-platform/4.7/post_installation_configuration/machine-configuration-tasks.html#machine-config-overview-post-install-machine-configuration-tasks
  ignition_version: "3.2.0"
ENV_DATA:
  # TODO: replace with 4.16 once template is available
  vm_template: "rhcos-415.92.202311241643-0-vmware.x86_64"
  acm_hub_channel: release-2.9
  acm_version: "2.9"
