---
# Config file for nightly OCP 4.10
RUN:
  client_version: "4.10.0-0.nightly"
DEPLOYMENT:
  installer_version: "4.10.0-0.nightly"
  terraform_version: "0.12.26"
  # ignition_version can be found here
  # https://docs.openshift.com/container-platform/4.7/post_installation_configuration/machine-configuration-tasks.html#machine-config-overview-post-install-machine-configuration-tasks
  ignition_version: "3.2.0"
ENV_DATA:
  vm_template: "rhcos-410.84.202201251210-0-vmware.x86_64"
  acm_hub_channel: release-2.5 # To be changed when acm 2.6 get's released
