---
# Config file for OCP GA 4.12 stable channel minus 1 version

RUN:
  client_version: '4.12-ga'

DEPLOYMENT:
  ocp_url_template: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{version}/{file_name}-{os_type}-{version}.tar.gz"
  installer_version: "4.12-ga"
  terraform_version: "0.12.26"
  ignition_version: "3.2.0"
  ocp_channel: "fast"
  ocp_version_index: -2
ENV_DATA:
  # TODO: This we will need to update to update to released version once we
  # will upload to DCs
  vm_template: "rhcos-4.12.0-x86_64-vmware.x86_64"
  acm_hub_channel: release-2.7
  acm_version: "2.7"
