---
# Config file for OCP GA 4.7 stable channel

RUN:
  client_version: '4.7-ga'

DEPLOYMENT:
  ocp_url_template: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{version}/{file_name}-{os_type}-{version}.tar.gz"
  installer_version: "4.7-ga"
  terraform_version: "0.12.31"
  # ignition_version can be found here
  # https://docs.openshift.com/container-platform/4.7/post_installation_configuration/machine-configuration-tasks.html#machine-config-overview-post-install-machine-configuration-tasks
  ignition_version: "3.2.0"
  ocp_channel: "stable"
  # No promoted content to stable-4.6 channel yet
  # Once the build promoted to stable, we can move to stable channel
ENV_DATA:
  vm_template: 'rhcos-4.7.0-x86_64-vmware.x86_64'
  # rhcos_ami: 'ami-06c85f9d106577272'
  # If rhcos_ami is not specified the ID for aws upi deployments will be fetched from
  # https://raw.githubusercontent.com/openshift/installer/release-4.5/data/data/rhcos.json
